# Generated by Django 4.1.5 on 2023-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_workout_reps1_alter_workout_reps2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.exercise'),
            preserve_default=False,
        ),
    ]
