# Generated by Django 4.1.7 on 2023-04-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_surname_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
