# Generated by Django 4.1.7 on 2023-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='descriptionLong',
            field=models.TextField(default='sieeema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
