# Generated by Django 4.1.7 on 2023-04-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
