# Generated by Django 4.1.7 on 2023-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_plans_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
