# Generated by Django 4.1.7 on 2023-05-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='User',
            new_name='user',
        ),
    ]
