# Generated by Django 4.1.7 on 2023-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_user_messages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
