# Generated by Django 4.1.7 on 2023-05-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_exercise_video_alter_userprofile_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='anwered',
            new_name='answered',
        ),
    ]
